package html

// generated by hasher -type=Hash -file=hash.go; DO NOT EDIT, except for adding more constants to the list and rerun go generate

// uses github.com/tdewolff/hasher
//go:generate hasher -type=Hash -file=hash.go

// Hash defines perfect hashes for a predefined list of strings
type Hash uint32

// Unique hash definitions to be used instead of strings
const (
	A                Hash = 0x1     // a
	Abbr             Hash = 0x4     // abbr
	Accept           Hash = 0x3206  // accept
	Accept_Charset   Hash = 0x320e  // accept-charset
	Accesskey        Hash = 0x4409  // accesskey
	Acronym          Hash = 0xbb07  // acronym
	Action           Hash = 0x2b906 // action
	Address          Hash = 0x67807 // address
	Align            Hash = 0x1605  // align
	Alink            Hash = 0xd205  // alink
	Allowfullscreen  Hash = 0x23c0f // allowfullscreen
	Alt              Hash = 0xeb03  // alt
	Annotation       Hash = 0x2060a // annotation
	AnnotationXml    Hash = 0x2060d // annotationXml
	Applet           Hash = 0x16106 // applet
	Area             Hash = 0x38d04 // area
	Article          Hash = 0x40e07 // article
	Aside            Hash = 0x8305  // aside
	Async            Hash = 0xf705  // async
	Audio            Hash = 0x11305 // audio
	Autocomplete     Hash = 0x14a0c // autocomplete
	Autofocus        Hash = 0x15609 // autofocus
	Autoplay         Hash = 0x16b08 // autoplay
	Axis             Hash = 0x17304 // axis
	B                Hash = 0x101   // b
	Background       Hash = 0x1e0a  // background
	Base             Hash = 0x45404 // base
	Basefont         Hash = 0x45408 // basefont
	Bdi              Hash = 0xcb03  // bdi
	Bdo              Hash = 0x18a03 // bdo
	Bgcolor          Hash = 0x19d07 // bgcolor
	Bgsound          Hash = 0x1a407 // bgsound
	Big              Hash = 0x1ac03 // big
	Blink            Hash = 0x1af05 // blink
	Blockquote       Hash = 0x1b40a // blockquote
	Body             Hash = 0x4004  // body
	Border           Hash = 0x33806 // border
	Br               Hash = 0x202   // br
	Button           Hash = 0x1be06 // button
	Canvas           Hash = 0x7f06  // canvas
	Caption          Hash = 0x27e07 // caption
	Center           Hash = 0x62506 // center
	Challenge        Hash = 0x1eb09 // challenge
	Charset          Hash = 0x3907  // charset
	Checked          Hash = 0x3b407 // checked
	Cite             Hash = 0xfb04  // cite
	Class            Hash = 0x1c905 // class
	Classid          Hash = 0x1c907 // classid
	Clear            Hash = 0x41205 // clear
	Code             Hash = 0x1dc04 // code
	Codebase         Hash = 0x45008 // codebase
	Codetype         Hash = 0x1dc08 // codetype
	Col              Hash = 0x19f03 // col
	Colgroup         Hash = 0x1f408 // colgroup
	Color            Hash = 0x19f05 // color
	Cols             Hash = 0x20104 // cols
	Colspan          Hash = 0x20107 // colspan
	Command          Hash = 0x21307 // command
	Compact          Hash = 0x21a07 // compact
	Content          Hash = 0x58807 // content
	Contenteditable  Hash = 0x5880f // contenteditable
	Contextmenu      Hash = 0x3bd0b // contextmenu
	Controls         Hash = 0x22908 // controls
	Coords           Hash = 0x23506 // coords
	Crossorigin      Hash = 0x25a0b // crossorigin
	Data             Hash = 0x4ad04 // data
	Datalist         Hash = 0x4ad08 // datalist
	Datetime         Hash = 0x2e908 // datetime
	Dd               Hash = 0x31602 // dd
	Declare          Hash = 0x8607  // declare
	Default          Hash = 0x5407  // default
	DefaultChecked   Hash = 0x4f10e // defaultChecked
	DefaultMuted     Hash = 0x5520c // defaultMuted
	DefaultSelected  Hash = 0x540f  // defaultSelected
	Defer            Hash = 0x6205  // defer
	Del              Hash = 0x7203  // del
	Desc             Hash = 0x7c04  // desc
	Details          Hash = 0x9207  // details
	Dfn              Hash = 0xab03  // dfn
	Dialog           Hash = 0xcc06  // dialog
	Dir              Hash = 0xd903  // dir
	Dirname          Hash = 0xd907  // dirname
	Disabled         Hash = 0x10108 // disabled
	Div              Hash = 0x10803 // div
	Dl               Hash = 0x1aa02 // dl
	Download         Hash = 0x48608 // download
	Draggable        Hash = 0x1cf09 // draggable
	Dropzone         Hash = 0x41908 // dropzone
	Dt               Hash = 0x60102 // dt
	Em               Hash = 0x6e02  // em
	Embed            Hash = 0x6e05  // embed
	Enabled          Hash = 0x4e07  // enabled
	Enctype          Hash = 0x2ce07 // enctype
	Face             Hash = 0x62304 // face
	Fieldset         Hash = 0x26b08 // fieldset
	Figcaption       Hash = 0x27b0a // figcaption
	Figure           Hash = 0x28f06 // figure
	Font             Hash = 0x45804 // font
	Footer           Hash = 0xee06  // footer
	For              Hash = 0x29b03 // for
	ForeignObject    Hash = 0x29b0d // foreignObject
	Foreignobject    Hash = 0x2a80d // foreignobject
	Form             Hash = 0x2b504 // form
	Formaction       Hash = 0x2b50a // formaction
	Formenctype      Hash = 0x2ca0b // formenctype
	Formmethod       Hash = 0x2d50a // formmethod
	Formnovalidate   Hash = 0x2df0e // formnovalidate
	Formtarget       Hash = 0x2f40a // formtarget
	Frame            Hash = 0xa305  // frame
	Frameborder      Hash = 0x3330b // frameborder
	Frameset         Hash = 0xa308  // frameset
	H1               Hash = 0x19b02 // h1
	H2               Hash = 0x32402 // h2
	H3               Hash = 0x34902 // h3
	H4               Hash = 0x38602 // h4
	H5               Hash = 0x60302 // h5
	H6               Hash = 0x2fe02 // h6
	Head             Hash = 0x37204 // head
	Header           Hash = 0x37206 // header
	Headers          Hash = 0x37207 // headers
	Height           Hash = 0x30006 // height
	Hgroup           Hash = 0x30806 // hgroup
	Hidden           Hash = 0x31406 // hidden
	High             Hash = 0x32104 // high
	Hr               Hash = 0xaf02  // hr
	Href             Hash = 0xaf04  // href
	Hreflang         Hash = 0xaf08  // hreflang
	Html             Hash = 0x30404 // html
	Http_Equiv       Hash = 0x3260a // http-equiv
	I                Hash = 0x601   // i
	Icon             Hash = 0x58704 // icon
	Id               Hash = 0x8502  // id
	Iframe           Hash = 0x33206 // iframe
	Image            Hash = 0x33e05 // image
	Img              Hash = 0x34303 // img
	Inert            Hash = 0x53d05 // inert
	Input            Hash = 0x47305 // input
	Ins              Hash = 0x26303 // ins
	Isindex          Hash = 0x17507 // isindex
	Ismap            Hash = 0x34b05 // ismap
	Itemid           Hash = 0xfc06  // itemid
	Itemprop         Hash = 0x57508 // itemprop
	Itemref          Hash = 0x61d07 // itemref
	Itemscope        Hash = 0x35609 // itemscope
	Itemtype         Hash = 0x36008 // itemtype
	Kbd              Hash = 0xca03  // kbd
	Keygen           Hash = 0x4a06  // keygen
	Keytype          Hash = 0x68207 // keytype
	Kind             Hash = 0xd604  // kind
	Label            Hash = 0x7405  // label
	Lang             Hash = 0xb304  // lang
	Language         Hash = 0xb308  // language
	Legend           Hash = 0x1d606 // legend
	Li               Hash = 0x1702  // li
	Link             Hash = 0xd304  // link
	List             Hash = 0x4b104 // list
	Listing          Hash = 0x4b107 // listing
	Longdesc         Hash = 0x7808  // longdesc
	Loop             Hash = 0x11e04 // loop
	Low              Hash = 0x23e03 // low
	Main             Hash = 0x1004  // main
	Malignmark       Hash = 0xc10a  // malignmark
	Manifest         Hash = 0x65908 // manifest
	Map              Hash = 0x16003 // map
	Mark             Hash = 0xc704  // mark
	Marquee          Hash = 0x36807 // marquee
	Math             Hash = 0x36f04 // math
	Max              Hash = 0x37e03 // max
	Maxlength        Hash = 0x37e09 // maxlength
	Media            Hash = 0xde05  // media
	Mediagroup       Hash = 0xde0a  // mediagroup
	Menu             Hash = 0x3c404 // menu
	Meta             Hash = 0x4c004 // meta
	Meter            Hash = 0x2ef05 // meter
	Method           Hash = 0x2d906 // method
	Mglyph           Hash = 0x34406 // mglyph
	Mi               Hash = 0x2c02  // mi
	Min              Hash = 0x2c03  // min
	Mn               Hash = 0x2e202 // mn
	Mo               Hash = 0x4e402 // mo
	Ms               Hash = 0x35902 // ms
	Mtext            Hash = 0x38805 // mtext
	Multiple         Hash = 0x39608 // multiple
	Muted            Hash = 0x39e05 // muted
	Name             Hash = 0xdc04  // name
	Nav              Hash = 0x1303  // nav
	Nobr             Hash = 0x1a04  // nobr
	Noembed          Hash = 0x6c07  // noembed
	Noframes         Hash = 0xa108  // noframes
	Nohref           Hash = 0xad06  // nohref
	Noresize         Hash = 0x24a08 // noresize
	Noscript         Hash = 0x31908 // noscript
	Noshade          Hash = 0x4ec07 // noshade
	Novalidate       Hash = 0x2e30a // novalidate
	Nowrap           Hash = 0x57e06 // nowrap
	Object           Hash = 0x2af06 // object
	Ol               Hash = 0x12d02 // ol
	Onabort          Hash = 0x1c207 // onabort
	Onafterprint     Hash = 0x2830c // onafterprint
	Onbeforeprint    Hash = 0x2bd0d // onbeforeprint
	Onbeforeunload   Hash = 0x66c0e // onbeforeunload
	Onblur           Hash = 0x14406 // onblur
	Oncancel         Hash = 0x11708 // oncancel
	Oncanplay        Hash = 0x18c09 // oncanplay
	Oncanplaythrough Hash = 0x18c10 // oncanplaythrough
	Onchange         Hash = 0x42f08 // onchange
	Onclick          Hash = 0x6b007 // onclick
	Onclose          Hash = 0x3a307 // onclose
	Oncontextmenu    Hash = 0x3bb0d // oncontextmenu
	Oncuechange      Hash = 0x3c80b // oncuechange
	Ondblclick       Hash = 0x3d30a // ondblclick
	Ondrag           Hash = 0x3dd06 // ondrag
	Ondragend        Hash = 0x3dd09 // ondragend
	Ondragenter      Hash = 0x3e60b // ondragenter
	Ondragleave      Hash = 0x3f10b // ondragleave
	Ondragover       Hash = 0x3fc0a // ondragover
	Ondragstart      Hash = 0x4060b // ondragstart
	Ondrop           Hash = 0x41706 // ondrop
	Ondurationchange Hash = 0x42710 // ondurationchange
	Onemptied        Hash = 0x41e09 // onemptied
	Onended          Hash = 0x43707 // onended
	Onerror          Hash = 0x43e07 // onerror
	Onfocus          Hash = 0x44507 // onfocus
	Onhashchange     Hash = 0x4650c // onhashchange
	Oninput          Hash = 0x47107 // oninput
	Oninvalid        Hash = 0x47809 // oninvalid
	Onkeydown        Hash = 0x48109 // onkeydown
	Onkeypress       Hash = 0x48e0a // onkeypress
	Onkeyup          Hash = 0x49e07 // onkeyup
	Onload           Hash = 0x4a506 // onload
	Onloadeddata     Hash = 0x4a50c // onloadeddata
	Onloadedmetadata Hash = 0x4b810 // onloadedmetadata
	Onloadstart      Hash = 0x4ce0b // onloadstart
	Onmessage        Hash = 0x4d909 // onmessage
	Onmousedown      Hash = 0x4e20b // onmousedown
	Onmousemove      Hash = 0x4ff0b // onmousemove
	Onmouseout       Hash = 0x50a0a // onmouseout
	Onmouseover      Hash = 0x5170b // onmouseover
	Onmouseup        Hash = 0x52209 // onmouseup
	Onmousewheel     Hash = 0x52b0c // onmousewheel
	Onoffline        Hash = 0x53709 // onoffline
	Ononline         Hash = 0x54208 // ononline
	Onpagehide       Hash = 0x54a0a // onpagehide
	Onpageshow       Hash = 0x55e0a // onpageshow
	Onpause          Hash = 0x56a07 // onpause
	Onplay           Hash = 0x59706 // onplay
	Onplaying        Hash = 0x59709 // onplaying
	Onpopstate       Hash = 0x5a00a // onpopstate
	Onprogress       Hash = 0x5aa0a // onprogress
	Onratechange     Hash = 0x5b90c // onratechange
	Onreset          Hash = 0x5c507 // onreset
	Onresize         Hash = 0x5cc08 // onresize
	Onscroll         Hash = 0x5d408 // onscroll
	Onseeked         Hash = 0x5df08 // onseeked
	Onseeking        Hash = 0x5e709 // onseeking
	Onselect         Hash = 0x5f008 // onselect
	Onshow           Hash = 0x5fa06 // onshow
	Onstalled        Hash = 0x60509 // onstalled
	Onstorage        Hash = 0x60e09 // onstorage
	Onsubmit         Hash = 0x61708 // onsubmit
	Onsuspend        Hash = 0x62b09 // onsuspend
	Ontimeupdate     Hash = 0x4590c // ontimeupdate
	Onunload         Hash = 0x63408 // onunload
	Onvolumechange   Hash = 0x63c0e // onvolumechange
	Onwaiting        Hash = 0x64a09 // onwaiting
	Open             Hash = 0x57b04 // open
	Optgroup         Hash = 0x12008 // optgroup
	Optimum          Hash = 0x65307 // optimum
	Option           Hash = 0x66806 // option
	Output           Hash = 0x51106 // output
	P                Hash = 0xc01   // p
	Param            Hash = 0xc05   // param
	Pattern          Hash = 0x9b07  // pattern
	Pauseonexit      Hash = 0x56c0b // pauseonexit
	Ping             Hash = 0xe704  // ping
	Placeholder      Hash = 0x1270b // placeholder
	Plaintext        Hash = 0x17d09 // plaintext
	Poster           Hash = 0x1fb06 // poster
	Pre              Hash = 0x30d03 // pre
	Preload          Hash = 0x30d07 // preload
	Profile          Hash = 0x34f07 // profile
	Progress         Hash = 0x5ac08 // progress
	Prompt           Hash = 0x66206 // prompt
	Public           Hash = 0x58306 // public
	Q                Hash = 0x8d01  // q
	Radiogroup       Hash = 0x30a   // radiogroup
	Rb               Hash = 0x1d02  // rb
	Readonly         Hash = 0x38e08 // readonly
	Rel              Hash = 0x30e03 // rel
	Required         Hash = 0x8b08  // required
	Rev              Hash = 0x29303 // rev
	Reversed         Hash = 0x29308 // reversed
	Rows             Hash = 0x6604  // rows
	Rowspan          Hash = 0x6607  // rowspan
	Rp               Hash = 0x28902 // rp
	Rt               Hash = 0x1c702 // rt
	Rtc              Hash = 0x1c703 // rtc
	Ruby             Hash = 0xf304  // ruby
	Rules            Hash = 0x13105 // rules
	S                Hash = 0x3d01  // s
	Samp             Hash = 0x9804  // samp
	Sandbox          Hash = 0x13507 // sandbox
	Scope            Hash = 0x35a05 // scope
	Scoped           Hash = 0x35a06 // scoped
	Script           Hash = 0x31b06 // script
	Scrolling        Hash = 0x5d609 // scrolling
	Seamless         Hash = 0x3a808 // seamless
	Section          Hash = 0x13f07 // section
	Select           Hash = 0x5f206 // select
	Selected         Hash = 0x5f208 // selected
	Shape            Hash = 0x23005 // shape
	Size             Hash = 0x24e04 // size
	Sizes            Hash = 0x24e05 // sizes
	Small            Hash = 0x23a05 // small
	Sortable         Hash = 0x25208 // sortable
	Source           Hash = 0x26506 // source
	Spacer           Hash = 0x37806 // spacer
	Span             Hash = 0x6904  // span
	Spellcheck       Hash = 0x3af0a // spellcheck
	Src              Hash = 0x44b03 // src
	Srcdoc           Hash = 0x44b06 // srcdoc
	Srclang          Hash = 0x49707 // srclang
	Srcset           Hash = 0x5b306 // srcset
	Start            Hash = 0x40c05 // start
	Step             Hash = 0x65f04 // step
	Strike           Hash = 0x67e06 // strike
	Strong           Hash = 0x68906 // strong
	Style            Hash = 0x68f05 // style
	Sub              Hash = 0x61903 // sub
	Summary          Hash = 0x69407 // summary
	Sup              Hash = 0x69b03 // sup
	Svg              Hash = 0x69e03 // svg
	System           Hash = 0x6a106 // system
	Tabindex         Hash = 0x4c608 // tabindex
	Table            Hash = 0x25505 // table
	Target           Hash = 0x2f806 // target
	Tbody            Hash = 0x3f05  // tbody
	Td               Hash = 0xaa02  // td
	Template         Hash = 0x6a408 // template
	Text             Hash = 0x18204 // text
	Textarea         Hash = 0x38908 // textarea
	Tfoot            Hash = 0xed05  // tfoot
	Th               Hash = 0x19502 // th
	Thead            Hash = 0x37105 // thead
	Time             Hash = 0x2ed04 // time
	Title            Hash = 0x16605 // title
	Tr               Hash = 0x18502 // tr
	Track            Hash = 0x18505 // track
	Translate        Hash = 0x22009 // translate
	Truespeed        Hash = 0x27209 // truespeed
	Tt               Hash = 0x9d02  // tt
	Type             Hash = 0x10f04 // type
	Typemustmatch    Hash = 0x1e00d // typemustmatch
	U                Hash = 0xb01   // u
	Ul               Hash = 0x5802  // ul
	Undeterminate    Hash = 0x250d  // undeterminate
	Usemap           Hash = 0x15d06 // usemap
	Valign           Hash = 0x1506  // valign
	Value            Hash = 0x10a05 // value
	Valuetype        Hash = 0x10a09 // valuetype
	Var              Hash = 0x32f03 // var
	Video            Hash = 0x6ac05 // video
	Visible          Hash = 0x6b707 // visible
	Vlink            Hash = 0x6be05 // vlink
	Wbr              Hash = 0x56703 // wbr
	Width            Hash = 0x5ff05 // width
	Wrap             Hash = 0x58004 // wrap
	Xmlns            Hash = 0x13b05 // xmlns
	Xmp              Hash = 0x17b03 // xmp
)

// String returns the hash' name.
func (i Hash) String() string {
	start := uint32(i >> 8)
	n := uint32(i & 0xff)
	if start+n > uint32(len(_Hash_text)) {
		return ""
	}
	return _Hash_text[start : start+n]
}

// ToHash returns the hash whose name is s. It returns zero if there is no
// such hash. It is case sensitive.
func ToHash(s []byte) Hash {
	if len(s) == 0 || len(s) > _Hash_maxLen {
		return 0
	}
	h := uint32(_Hash_hash0)
	for i := 0; i < len(s); i++ {
		h ^= uint32(s[i])
		h *= 16777619
	}
	if i := _Hash_table[h&uint32(len(_Hash_table)-1)]; int(i&0xff) == len(s) {
		t := _Hash_text[i>>8 : i>>8+i&0xff]
		for i := 0; i < len(s); i++ {
			if t[i] != s[i] {
				goto NEXT
			}
		}
		return i
	}
NEXT:
	if i := _Hash_table[(h>>16)&uint32(len(_Hash_table)-1)]; int(i&0xff) == len(s) {
		t := _Hash_text[i>>8 : i>>8+i&0xff]
		for i := 0; i < len(s); i++ {
			if t[i] != s[i] {
				return 0
			}
		}
		return i
	}
	return 0
}

const _Hash_hash0 = 0x5334b67c
const _Hash_maxLen = 16
const _Hash_text = "abbradiogrouparamainavalignobrbackgroundeterminateaccept-cha" +
	"rsetbodyaccesskeygenabledefaultSelectedeferowspanoembedelabe" +
	"longdescanvasideclarequiredetailsampatternoframesetdfnohrefl" +
	"anguageacronymalignmarkbdialogalinkindirnamediagroupingaltfo" +
	"oterubyasyncitemidisabledivaluetypeaudioncancelooptgrouplace" +
	"holderulesandboxmlnsectionblurautocompleteautofocusemappleti" +
	"tleautoplayaxisindexmplaintextrackbdoncanplaythrough1bgcolor" +
	"bgsoundlbigblinkblockquotebuttonabortclassidraggablegendcode" +
	"typemustmatchallengecolgroupostercolspannotationXmlcommandco" +
	"mpactranslatecontrolshapecoordsmallowfullscreenoresizesortab" +
	"lecrossoriginsourcefieldsetruespeedfigcaptionafterprintfigur" +
	"eversedforeignObjectforeignobjectformactionbeforeprintformen" +
	"ctypeformmethodformnovalidatetimeterformtargeth6heightmlhgro" +
	"upreloadhiddenoscripthigh2http-equivariframeborderimageimgly" +
	"ph3ismaprofileitemscopeditemtypemarqueematheaderspacermaxlen" +
	"gth4mtextareadonlymultiplemutedoncloseamlesspellcheckedoncon" +
	"textmenuoncuechangeondblclickondragendondragenterondragleave" +
	"ondragoverondragstarticlearondropzonemptiedondurationchangeo" +
	"nendedonerroronfocusrcdocodebasefontimeupdateonhashchangeoni" +
	"nputoninvalidonkeydownloadonkeypressrclangonkeyuponloadeddat" +
	"alistingonloadedmetadatabindexonloadstartonmessageonmousedow" +
	"noshadefaultCheckedonmousemoveonmouseoutputonmouseoveronmous" +
	"euponmousewheelonofflinertononlineonpagehidefaultMutedonpage" +
	"showbronpauseonexitempropenowrapublicontenteditableonplaying" +
	"onpopstateonprogressrcsetonratechangeonresetonresizeonscroll" +
	"ingonseekedonseekingonselectedonshowidth5onstalledonstorageo" +
	"nsubmitemrefacenteronsuspendonunloadonvolumechangeonwaitingo" +
	"ptimumanifestepromptoptionbeforeunloaddresstrikeytypestrongs" +
	"tylesummarysupsvgsystemplatevideonclickvisiblevlink"

var _Hash_table = [1 << 9]Hash{
	0x0:   0x2ca0b, // formenctype
	0x1:   0x2d50a, // formmethod
	0x2:   0x3c80b, // oncuechange
	0x3:   0x3dd06, // ondrag
	0x6:   0x67e06, // strike
	0x7:   0x6ac05, // video
	0x9:   0x58807, // content
	0xa:   0x4e07,  // enabled
	0xb:   0x57e06, // nowrap
	0xc:   0xd304,  // link
	0xe:   0x28902, // rp
	0xf:   0x2830c, // onafterprint
	0x10:  0x16106, // applet
	0x11:  0xed05,  // tfoot
	0x12:  0x4f10e, // defaultChecked
	0x13:  0x3330b, // frameborder
	0x14:  0xee06,  // footer
	0x15:  0x5f208, // selected
	0x16:  0x49707, // srclang
	0x18:  0x5170b, // onmouseover
	0x19:  0x1dc04, // code
	0x1b:  0x47809, // oninvalid
	0x1c:  0x62304, // face
	0x1e:  0x3bd0b, // contextmenu
	0x1f:  0xa308,  // frameset
	0x21:  0x5520c, // defaultMuted
	0x22:  0x19f05, // color
	0x23:  0x59706, // onplay
	0x25:  0x2ef05, // meter
	0x26:  0x60e09, // onstorage
	0x27:  0x38e08, // readonly
	0x29:  0x34f07, // profile
	0x2a:  0x8607,  // declare
	0x2b:  0xb01,   // u
	0x2c:  0x31908, // noscript
	0x2d:  0x65908, // manifest
	0x2e:  0x1be06, // button
	0x2f:  0x2e908, // datetime
	0x30:  0x47305, // input
	0x31:  0x5407,  // default
	0x32:  0x1dc08, // codetype
	0x33:  0x2a80d, // foreignobject
	0x34:  0x36807, // marquee
	0x36:  0x19d07, // bgcolor
	0x37:  0x19b02, // h1
	0x39:  0x1e0a,  // background
	0x3b:  0x2f40a, // formtarget
	0x41:  0x2f806, // target
	0x43:  0x23a05, // small
	0x44:  0x45008, // codebase
	0x45:  0x53d05, // inert
	0x47:  0x38805, // mtext
	0x48:  0x6607,  // rowspan
	0x49:  0x2bd0d, // onbeforeprint
	0x4a:  0x54208, // ononline
	0x4c:  0x28f06, // figure
	0x4d:  0x4b810, // onloadedmetadata
	0x4e:  0xbb07,  // acronym
	0x50:  0x39608, // multiple
	0x51:  0x320e,  // accept-charset
	0x52:  0x24e05, // sizes
	0x53:  0x29b0d, // foreignObject
	0x55:  0x2e30a, // novalidate
	0x56:  0x54a0a, // onpagehide
	0x57:  0x2e202, // mn
	0x58:  0x38602, // h4
	0x5a:  0x1c702, // rt
	0x5b:  0xd205,  // alink
	0x5e:  0x66206, // prompt
	0x5f:  0x12d02, // ol
	0x61:  0x5cc08, // onresize
	0x64:  0x69407, // summary
	0x65:  0x5a00a, // onpopstate
	0x66:  0x38d04, // area
	0x68:  0x64a09, // onwaiting
	0x6b:  0xdc04,  // name
	0x6c:  0x23506, // coords
	0x6d:  0x34303, // img
	0x6e:  0x65f04, // step
	0x6f:  0x5e709, // onseeking
	0x70:  0x32104, // high
	0x71:  0x49e07, // onkeyup
	0x72:  0x5f206, // select
	0x73:  0x18505, // track
	0x74:  0x34b05, // ismap
	0x76:  0x47107, // oninput
	0x77:  0x8d01,  // q
	0x78:  0x48109, // onkeydown
	0x79:  0x33e05, // image
	0x7a:  0x2b504, // form
	0x7b:  0x60509, // onstalled
	0x7d:  0x42f08, // onchange
	0x7e:  0x1af05, // blink
	0x7f:  0xeb03,  // alt
	0x80:  0xf705,  // async
	0x82:  0x1702,  // li
	0x84:  0x2c02,  // mi
	0x85:  0xfc06,  // itemid
	0x86:  0x11305, // audio
	0x87:  0x31b06, // script
	0x8b:  0x44b06, // srcdoc
	0x8e:  0xc704,  // mark
	0x8f:  0x18a03, // bdo
	0x91:  0x4ff0b, // onmousemove
	0x93:  0x3c404, // menu
	0x94:  0x45804, // font
	0x95:  0x16b08, // autoplay
	0x96:  0x6be05, // vlink
	0x98:  0x6e02,  // em
	0x9a:  0x5b306, // srcset
	0x9b:  0x1f408, // colgroup
	0x9c:  0x57b04, // open
	0x9d:  0x1d606, // legend
	0x9e:  0x4ce0b, // onloadstart
	0xa2:  0x22009, // translate
	0xa3:  0x6e05,  // embed
	0xa4:  0x1c905, // class
	0xa6:  0x6a408, // template
	0xa7:  0x37206, // header
	0xa9:  0x4a506, // onload
	0xaa:  0x37105, // thead
	0xab:  0x5d609, // scrolling
	0xac:  0xc05,   // param
	0xae:  0x9b07,  // pattern
	0xaf:  0x9207,  // details
	0xb1:  0x58306, // public
	0xb3:  0x4e20b, // onmousedown
	0xb4:  0x16003, // map
	0xb6:  0x25a0b, // crossorigin
	0xb7:  0x1506,  // valign
	0xb9:  0x1c207, // onabort
	0xba:  0x66806, // option
	0xbb:  0x26506, // source
	0xbc:  0x6205,  // defer
	0xbd:  0x1eb09, // challenge
	0xbf:  0x10a05, // value
	0xc0:  0x23c0f, // allowfullscreen
	0xc1:  0xca03,  // kbd
	0xc2:  0x2060d, // annotationXml
	0xc3:  0x5b90c, // onratechange
	0xc4:  0x4e402, // mo
	0xc6:  0x3af0a, // spellcheck
	0xc7:  0x2c03,  // min
	0xc8:  0x4a50c, // onloadeddata
	0xc9:  0x41205, // clear
	0xca:  0x42710, // ondurationchange
	0xcb:  0x1a04,  // nobr
	0xcd:  0x27209, // truespeed
	0xcf:  0x30806, // hgroup
	0xd0:  0x40c05, // start
	0xd3:  0x41908, // dropzone
	0xd5:  0x7405,  // label
	0xd8:  0xde0a,  // mediagroup
	0xd9:  0x14406, // onblur
	0xdb:  0x27e07, // caption
	0xdd:  0x7c04,  // desc
	0xde:  0x13b05, // xmlns
	0xdf:  0x30006, // height
	0xe0:  0x21307, // command
	0xe2:  0x56c0b, // pauseonexit
	0xe3:  0x68906, // strong
	0xe4:  0x43e07, // onerror
	0xe5:  0x61708, // onsubmit
	0xe6:  0xb308,  // language
	0xe7:  0x48608, // download
	0xe9:  0x52209, // onmouseup
	0xec:  0x2ce07, // enctype
	0xed:  0x5f008, // onselect
	0xee:  0x2af06, // object
	0xef:  0x17d09, // plaintext
	0xf0:  0x3d30a, // ondblclick
	0xf1:  0x18c10, // oncanplaythrough
	0xf2:  0xd903,  // dir
	0xf3:  0x38908, // textarea
	0xf4:  0xe704,  // ping
	0xf5:  0x2d906, // method
	0xf6:  0x22908, // controls
	0xf7:  0x37806, // spacer
	0xf8:  0x69e03, // svg
	0xf9:  0x30404, // html
	0xfa:  0x3d01,  // s
	0xfc:  0xcc06,  // dialog
	0xfe:  0x1e00d, // typemustmatch
	0xff:  0x3b407, // checked
	0x101: 0x1fb06, // poster
	0x102: 0x3260a, // http-equiv
	0x103: 0x44b03, // src
	0x104: 0x10108, // disabled
	0x105: 0x37207, // headers
	0x106: 0x5aa0a, // onprogress
	0x107: 0x26b08, // fieldset
	0x108: 0x32f03, // var
	0x10a: 0xa305,  // frame
	0x10b: 0x36008, // itemtype
	0x10c: 0x3fc0a, // ondragover
	0x10d: 0x15609, // autofocus
	0x10f: 0x601,   // i
	0x110: 0x35902, // ms
	0x111: 0x45404, // base
	0x113: 0x35a05, // scope
	0x114: 0x3206,  // accept
	0x115: 0x57508, // itemprop
	0x117: 0xfb04,  // cite
	0x118: 0x3907,  // charset
	0x119: 0x16605, // title
	0x11a: 0x68207, // keytype
	0x11b: 0x18204, // text
	0x11c: 0x65307, // optimum
	0x11e: 0x37204, // head
	0x121: 0x21a07, // compact
	0x123: 0x62b09, // onsuspend
	0x124: 0x4b104, // list
	0x125: 0x4590c, // ontimeupdate
	0x126: 0x62506, // center
	0x127: 0x31406, // hidden
	0x129: 0x35609, // itemscope
	0x12c: 0x1aa02, // dl
	0x12d: 0x13f07, // section
	0x12e: 0x11708, // oncancel
	0x12f: 0x6b007, // onclick
	0x130: 0xde05,  // media
	0x131: 0x51106, // output
	0x132: 0x4ad08, // datalist
	0x133: 0x52b0c, // onmousewheel
	0x134: 0x45408, // basefont
	0x135: 0x37e09, // maxlength
	0x136: 0x6b707, // visible
	0x137: 0x2df0e, // formnovalidate
	0x139: 0x17b03, // xmp
	0x13a: 0x101,   // b
	0x13b: 0x55e0a, // onpageshow
	0x13c: 0xf304,  // ruby
	0x13d: 0x1270b, // placeholder
	0x13e: 0x4b107, // listing
	0x140: 0x26303, // ins
	0x141: 0x61d07, // itemref
	0x144: 0x540f,  // defaultSelected
	0x146: 0x3f10b, // ondragleave
	0x147: 0x1b40a, // blockquote
	0x148: 0x58004, // wrap
	0x14a: 0x1ac03, // big
	0x14b: 0x30e03, // rel
	0x14c: 0x41706, // ondrop
	0x14e: 0x6a106, // system
	0x14f: 0x30a,   // radiogroup
	0x150: 0x25505, // table
	0x152: 0x56703, // wbr
	0x153: 0x3bb0d, // oncontextmenu
	0x155: 0x250d,  // undeterminate
	0x157: 0x20104, // cols
	0x158: 0x13507, // sandbox
	0x159: 0x1303,  // nav
	0x15a: 0x37e03, // max
	0x15b: 0x7808,  // longdesc
	0x15c: 0x5ff05, // width
	0x15d: 0x34902, // h3
	0x15e: 0x1a407, // bgsound
	0x161: 0x10a09, // valuetype
	0x162: 0x68f05, // style
	0x164: 0x3f05,  // tbody
	0x165: 0x40e07, // article
	0x169: 0xcb03,  // bdi
	0x16a: 0x67807, // address
	0x16b: 0x23005, // shape
	0x16c: 0x2b906, // action
	0x16e: 0x18502, // tr
	0x16f: 0xaa02,  // td
	0x170: 0x3dd09, // ondragend
	0x171: 0x5802,  // ul
	0x172: 0x33806, // border
	0x174: 0x4a06,  // keygen
	0x175: 0x4004,  // body
	0x177: 0x1cf09, // draggable
	0x178: 0x2b50a, // formaction
	0x17b: 0x34406, // mglyph
	0x17d: 0x1d02,  // rb
	0x17e: 0x2fe02, // h6
	0x17f: 0x41e09, // onemptied
	0x180: 0x5c507, // onreset
	0x181: 0x1004,  // main
	0x182: 0x11e04, // loop
	0x183: 0x48e0a, // onkeypress
	0x184: 0x9d02,  // tt
	0x186: 0x20107, // colspan
	0x188: 0x36f04, // math
	0x189: 0x1605,  // align
	0x18a: 0xa108,  // noframes
	0x18b: 0xaf02,  // hr
	0x18c: 0xc10a,  // malignmark
	0x18e: 0x23e03, // low
	0x18f: 0x8502,  // id
	0x190: 0x6604,  // rows
	0x191: 0x29303, // rev
	0x192: 0x63408, // onunload
	0x193: 0x39e05, // muted
	0x194: 0x35a06, // scoped
	0x195: 0x31602, // dd
	0x196: 0x60102, // dt
	0x197: 0x66c0e, // onbeforeunload
	0x199: 0x2060a, // annotation
	0x19a: 0x29308, // reversed
	0x19c: 0x10f04, // type
	0x19d: 0x56a07, // onpause
	0x19e: 0xd604,  // kind
	0x19f: 0x4ad04, // data
	0x1a0: 0x4ec07, // noshade
	0x1a3: 0x13105, // rules
	0x1a4: 0x12008, // optgroup
	0x1a5: 0x202,   // br
	0x1a7: 0x1,     // a
	0x1a8: 0x50a0a, // onmouseout
	0x1aa: 0x53709, // onoffline
	0x1ab: 0x63c0e, // onvolumechange
	0x1ae: 0x61903, // sub
	0x1b3: 0x29b03, // for
	0x1b5: 0x8b08,  // required
	0x1b6: 0x5ac08, // progress
	0x1b7: 0x15d06, // usemap
	0x1b8: 0x7f06,  // canvas
	0x1b9: 0x58704, // icon
	0x1bb: 0x1c703, // rtc
	0x1bc: 0x8305,  // aside
	0x1bd: 0x2ed04, // time
	0x1be: 0x4060b, // ondragstart
	0x1c0: 0x27b0a, // figcaption
	0x1c1: 0xaf04,  // href
	0x1c2: 0x33206, // iframe
	0x1c3: 0x18c09, // oncanplay
	0x1c4: 0x6904,  // span
	0x1c5: 0x30d03, // pre
	0x1c6: 0x6c07,  // noembed
	0x1c8: 0x5df08, // onseeked
	0x1c9: 0x4c004, // meta
	0x1ca: 0x32402, // h2
	0x1cb: 0x3a808, // seamless
	0x1cc: 0xab03,  // dfn
	0x1cd: 0x17304, // axis
	0x1cf: 0x3e60b, // ondragenter
	0x1d0: 0x19502, // th
	0x1d1: 0x4650c, // onhashchange
	0x1d2: 0xb304,  // lang
	0x1d3: 0x44507, // onfocus
	0x1d5: 0x24e04, // size
	0x1d8: 0x14a0c, // autocomplete
	0x1d9: 0xaf08,  // hreflang
	0x1da: 0x9804,  // samp
	0x1de: 0x19f03, // col
	0x1df: 0x10803, // div
	0x1e0: 0x25208, // sortable
	0x1e1: 0x7203,  // del
	0x1e3: 0x3a307, // onclose
	0x1e6: 0xd907,  // dirname
	0x1e8: 0x1c907, // classid
	0x1e9: 0x30d07, // preload
	0x1ea: 0x4c608, // tabindex
	0x1eb: 0x60302, // h5
	0x1ec: 0x5d408, // onscroll
	0x1ed: 0x5880f, // contenteditable
	0x1ee: 0x4d909, // onmessage
	0x1ef: 0x4,     // abbr
	0x1f0: 0x17507, // isindex
	0x1f1: 0x69b03, // sup
	0x1f3: 0x24a08, // noresize
	0x1f5: 0x59709, // onplaying
	0x1f6: 0x4409,  // accesskey
	0x1fa: 0xc01,   // p
	0x1fb: 0x43707, // onended
	0x1fc: 0x5fa06, // onshow
	0x1fe: 0xad06,  // nohref
}
