// generated by hasher -type=Hash -file=hash.go; DO NOT EDIT
package html

// github.com/tdewolff/hasher
//go:generate hasher -type=Hash -file=hash.go
type Hash uint32

// String returns the hash' name.
func (i Hash) String() string {
	start := uint32(i >> 8)
	n := uint32(i & 0xff)
	if start+n > uint32(len(_Hash_text)) {
		return ""
	}
	return _Hash_text[start : start+n]
}

// Hash returns the hash whose name is s. It returns zero if there is no
// such hash. It is case sensitive.
func ToHash(s []byte) Hash {
	if len(s) == 0 || len(s) > _Hash_maxLen {
		return 0
	}
	h := _Hash_fnv(s)
	if i := _Hash_table[h&uint32(len(_Hash_table)-1)]; int(i&0xff) == len(s) && _Hash_match(_Hash_string(i), s) {
		return i
	}
	if i := _Hash_table[(h>>16)&uint32(len(_Hash_table)-1)]; int(i&0xff) == len(s) && _Hash_match(_Hash_string(i), s) {
		return i
	}
	return 0
}

// _Hash_fnv computes the FNV hash with an arbitrary starting value h.
func _Hash_fnv(s []byte) uint32 {
	h := uint32(_Hash_hash0)
	for i := range s {
		h ^= uint32(s[i])
		h *= 16777619
	}
	return h
}

func _Hash_match(s string, t []byte) bool {
	for i, c := range t {
		if s[i] != c {
			return false
		}
	}
	return true
}

func _Hash_string(i Hash) string {
	return _Hash_text[i>>8 : i>>8+i&0xff]
}

const _Hash_hash0 = 0x55516c88
const _Hash_maxLen = 16
const _Hash_text = "abbradiogrouparamalignmarkbdialogaccept-charsetbodyaccesskey" +
	"genabledefaultSelectedeferowspanavalignobrubyacronymanifeste" +
	"patternoembedelabelongdescanvasideclarequiredetailsampingali" +
	"nkindfnoframesetdirnamediagrouplaceholderulesandboxmlnsectio" +
	"nbluraltfooterasyncitemidisabledivaluetypeaudioncancelooptgr" +
	"ouplaintextitleautocompleteautofocusemappletrackautoplayaxis" +
	"indexmposterbackgroundeterminatebdoncanplaythrough1bgcolorbg" +
	"soundlbigblinkblockquotebuttonabortranslatecodebasefontimeup" +
	"datecodetypemustmatchallengecolgroupreloadcolspannotationXml" +
	"commandcompactruespeedcontrolshapecoordsmallowfullscreenohre" +
	"flanguagecrossoriginsortablefieldsetfigcaptionafterprintfigu" +
	"reversedforeignObjectforeignobjectformactionbeforeprintforme" +
	"nctypeformmethodformnovalidatetimeterformtargeth6heightmlhgr" +
	"ouprofilehiddenoresizesourcehigh2http-equivariframeborderima" +
	"geimglyph3ismapromptitemscopeditemtypemaxlength4mtextareadon" +
	"lymultiplemutednowrapublicontenteditableoncloseamlesspellche" +
	"ckedoncontextmenuoncuechangeondblclickondragendondragenteron" +
	"dragleaveondragoverondragstarticlearondropzonemptiedondurati" +
	"onchangeonendedonerroronfocusrcdoclassidraggablegendonhashch" +
	"angeoninputoninvalidonkeydownloadonkeypressrclangonkeyuponlo" +
	"adeddatalistingonloadedmetadatabindexonloadstartonmessageonm" +
	"ousedownoscriptonmousemoveonmouseoutputonmouseoveronmouseupo" +
	"nmousewheelonofflinertononlineonpagehidefaultMutedonpageshow" +
	"bronpauseonexitempropenoshadefaultCheckedonplayingonpopstate" +
	"onprogresstrikeytypeonratechangeonresetonresizeonscrollingon" +
	"seekedonseekingonselectedonshowidth5onstalledonstorageonsubm" +
	"itemrefacenteronsuspendonunloadonvolumechangeonwaitingoptimu" +
	"marqueeoptionbeforeunloaddresstrongstylesummarysupsvgsystema" +
	"theaderspacervideonclickvisiblevlink"

const (
	A                Hash = 0x1
	Abbr             Hash = 0x4
	Accept           Hash = 0x2106
	Accept_Charset   Hash = 0x210e
	Accesskey        Hash = 0x3309
	Acronym          Hash = 0x6907
	Action           Hash = 0x2ba06
	Address          Hash = 0x66b07
	Align            Hash = 0x1105
	Alink            Hash = 0xb105
	Allowfullscreen  Hash = 0x2450f
	Alt              Hash = 0xf503
	Annotation       Hash = 0x20f0a
	AnnotationXml    Hash = 0x20f0d
	Applet           Hash = 0x15206
	Area             Hash = 0x37d04
	Article          Hash = 0x41707
	Aside            Hash = 0x9505
	Async            Hash = 0xfe05
	Audio            Hash = 0x11a05
	Autocomplete     Hash = 0x13b0c
	Autofocus        Hash = 0x14709
	Autoplay         Hash = 0x15c08
	Axis             Hash = 0x16404
	B                Hash = 0x101
	Background       Hash = 0x1740a
	Base             Hash = 0x1d304
	Basefont         Hash = 0x1d308
	Bdi              Hash = 0x1a03
	Bdo              Hash = 0x18803
	Bgcolor          Hash = 0x19b07
	Bgsound          Hash = 0x1a207
	Big              Hash = 0x1aa03
	Blink            Hash = 0x1ad05
	Blockquote       Hash = 0x1b20a
	Body             Hash = 0x2f04
	Border           Hash = 0x33f06
	Br               Hash = 0x202
	Button           Hash = 0x1bc06
	Canvas           Hash = 0x9106
	Caption          Hash = 0x27f07
	Center           Hash = 0x62006
	Challenge        Hash = 0x1f309
	Charset          Hash = 0x2807
	Checked          Hash = 0x3bd07
	Cite             Hash = 0x10204
	Class            Hash = 0x45905
	Classid          Hash = 0x45907
	Clear            Hash = 0x41b05
	Code             Hash = 0x1cf04
	Codebase         Hash = 0x1cf08
	Codetype         Hash = 0x1e408
	Col              Hash = 0x19d03
	Colgroup         Hash = 0x1fc08
	Color            Hash = 0x19d05
	Cols             Hash = 0x20a04
	Colspan          Hash = 0x20a07
	Command          Hash = 0x21c07
	Compact          Hash = 0x22307
	Content          Hash = 0x39d07
	Contenteditable  Hash = 0x39d0f
	Contextmenu      Hash = 0x3c60b
	Controls         Hash = 0x23208
	Coords           Hash = 0x23e06
	Crossorigin      Hash = 0x2610b
	Data             Hash = 0x4b404
	Datalist         Hash = 0x4b408
	Datetime         Hash = 0x2ea08
	Dd               Hash = 0x31702
	Declare          Hash = 0x9807
	Default          Hash = 0x4307
	DefaultChecked   Hash = 0x57f0e
	DefaultMuted     Hash = 0x54e0c
	DefaultSelected  Hash = 0x430f
	Defer            Hash = 0x5105
	Del              Hash = 0x8403
	Desc             Hash = 0x8e04
	Details          Hash = 0xa407
	Dfn              Hash = 0xb803
	Dialog           Hash = 0x1b06
	Dir              Hash = 0xc403
	Dirname          Hash = 0xc407
	Disabled         Hash = 0x10808
	Div              Hash = 0x10f03
	Dl               Hash = 0x1a802
	Download         Hash = 0x48d08
	Draggable        Hash = 0x45f09
	Dropzone         Hash = 0x42208
	Dt               Hash = 0x5fc02
	Em               Hash = 0x8002
	Embed            Hash = 0x8005
	Enabled          Hash = 0x3d07
	Enctype          Hash = 0x2cf07
	Face             Hash = 0x61e04
	Fieldset         Hash = 0x27408
	Figcaption       Hash = 0x27c0a
	Figure           Hash = 0x29006
	Font             Hash = 0x1d704
	Footer           Hash = 0xf806
	For              Hash = 0x29c03
	ForeignObject    Hash = 0x29c0d
	Foreignobject    Hash = 0x2a90d
	Form             Hash = 0x2b604
	Formaction       Hash = 0x2b60a
	Formenctype      Hash = 0x2cb0b
	Formmethod       Hash = 0x2d60a
	Formnovalidate   Hash = 0x2e00e
	Formtarget       Hash = 0x2f50a
	Frame            Hash = 0xbc05
	Frameborder      Hash = 0x33a0b
	Frameset         Hash = 0xbc08
	H1               Hash = 0x19902
	H2               Hash = 0x32b02
	H3               Hash = 0x35002
	H4               Hash = 0x37602
	H5               Hash = 0x5fe02
	H6               Hash = 0x2ff02
	Head             Hash = 0x69104
	Header           Hash = 0x69106
	Headers          Hash = 0x69107
	Height           Hash = 0x30106
	Hgroup           Hash = 0x30906
	Hidden           Hash = 0x31506
	High             Hash = 0x32804
	Hr               Hash = 0x19402
	Href             Hash = 0x25504
	Hreflang         Hash = 0x25508
	Html             Hash = 0x30504
	Http_Equiv       Hash = 0x32d0a
	I                Hash = 0x601
	Icon             Hash = 0x39c04
	Id               Hash = 0x9702
	Iframe           Hash = 0x33906
	Image            Hash = 0x34505
	Img              Hash = 0x34a03
	Inert            Hash = 0x53905
	Input            Hash = 0x47a05
	Ins              Hash = 0x26a03
	Isindex          Hash = 0x16607
	Ismap            Hash = 0x35205
	Itemid           Hash = 0x10306
	Itemprop         Hash = 0x57108
	Itemref          Hash = 0x61807
	Itemscope        Hash = 0x35c09
	Itemtype         Hash = 0x36608
	Kbd              Hash = 0x1903
	Keygen           Hash = 0x3906
	Keytype          Hash = 0x5ad07
	Kind             Hash = 0xb504
	Label            Hash = 0x8605
	Lang             Hash = 0x25904
	Language         Hash = 0x25908
	Legend           Hash = 0x46606
	Li               Hash = 0x1202
	Link             Hash = 0xb204
	List             Hash = 0x4b804
	Listing          Hash = 0x4b807
	Longdesc         Hash = 0x8a08
	Loop             Hash = 0x12504
	Low              Hash = 0x24703
	Malignmark       Hash = 0x100a
	Manifest         Hash = 0x6f08
	Map              Hash = 0x15103
	Mark             Hash = 0x1604
	Marquee          Hash = 0x65407
	Math             Hash = 0x68e04
	Max              Hash = 0x36e03
	Maxlength        Hash = 0x36e09
	Media            Hash = 0xc905
	Mediagroup       Hash = 0xc90a
	Menu             Hash = 0x3cd04
	Meta             Hash = 0x4c704
	Meter            Hash = 0x2f005
	Method           Hash = 0x2da06
	Mglyph           Hash = 0x34b06
	Mi               Hash = 0x10602
	Min              Hash = 0x18203
	Mn               Hash = 0x2e302
	Mo               Hash = 0x4eb02
	Ms               Hash = 0x35f02
	Mtext            Hash = 0x37805
	Multiple         Hash = 0x38608
	Muted            Hash = 0x38e05
	Name             Hash = 0xc704
	Nav              Hash = 0x5b03
	Nobr             Hash = 0x6204
	Noembed          Hash = 0x7e07
	Noframes         Hash = 0xba08
	Nohref           Hash = 0x25306
	Noresize         Hash = 0x31a08
	Noscript         Hash = 0x4f308
	Noshade          Hash = 0x57a07
	Novalidate       Hash = 0x2e40a
	Nowrap           Hash = 0x39306
	Object           Hash = 0x2b006
	Ol               Hash = 0xd802
	Onabort          Hash = 0x1c007
	Onafterprint     Hash = 0x2840c
	Onbeforeprint    Hash = 0x2be0d
	Onbeforeunload   Hash = 0x65f0e
	Onblur           Hash = 0xef06
	Oncancel         Hash = 0x11e08
	Oncanplay        Hash = 0x18a09
	Oncanplaythrough Hash = 0x18a10
	Onchange         Hash = 0x43808
	Onclick          Hash = 0x6a107
	Onclose          Hash = 0x3ac07
	Oncontextmenu    Hash = 0x3c40d
	Oncuechange      Hash = 0x3d10b
	Ondblclick       Hash = 0x3dc0a
	Ondrag           Hash = 0x3e606
	Ondragend        Hash = 0x3e609
	Ondragenter      Hash = 0x3ef0b
	Ondragleave      Hash = 0x3fa0b
	Ondragover       Hash = 0x4050a
	Ondragstart      Hash = 0x40f0b
	Ondrop           Hash = 0x42006
	Ondurationchange Hash = 0x43010
	Onemptied        Hash = 0x42709
	Onended          Hash = 0x44007
	Onerror          Hash = 0x44707
	Onfocus          Hash = 0x44e07
	Onhashchange     Hash = 0x46c0c
	Oninput          Hash = 0x47807
	Oninvalid        Hash = 0x47f09
	Onkeydown        Hash = 0x48809
	Onkeypress       Hash = 0x4950a
	Onkeyup          Hash = 0x4a507
	Onload           Hash = 0x4ac06
	Onloadeddata     Hash = 0x4ac0c
	Onloadedmetadata Hash = 0x4bf10
	Onloadstart      Hash = 0x4d50b
	Onmessage        Hash = 0x4e009
	Onmousedown      Hash = 0x4e90b
	Onmousemove      Hash = 0x4fb0b
	Onmouseout       Hash = 0x5060a
	Onmouseover      Hash = 0x5130b
	Onmouseup        Hash = 0x51e09
	Onmousewheel     Hash = 0x5270c
	Onoffline        Hash = 0x53309
	Ononline         Hash = 0x53e08
	Onpagehide       Hash = 0x5460a
	Onpageshow       Hash = 0x55a0a
	Onpause          Hash = 0x56607
	Onplay           Hash = 0x58d06
	Onplaying        Hash = 0x58d09
	Onpopstate       Hash = 0x5960a
	Onprogress       Hash = 0x5a00a
	Onratechange     Hash = 0x5b40c
	Onreset          Hash = 0x5c007
	Onresize         Hash = 0x5c708
	Onscroll         Hash = 0x5cf08
	Onseeked         Hash = 0x5da08
	Onseeking        Hash = 0x5e209
	Onselect         Hash = 0x5eb08
	Onshow           Hash = 0x5f506
	Onstalled        Hash = 0x60009
	Onstorage        Hash = 0x60909
	Onsubmit         Hash = 0x61208
	Onsuspend        Hash = 0x62609
	Ontimeupdate     Hash = 0x1d80c
	Onunload         Hash = 0x62f08
	Onvolumechange   Hash = 0x6370e
	Onwaiting        Hash = 0x64509
	Open             Hash = 0x57704
	Optgroup         Hash = 0x12708
	Optimum          Hash = 0x64e07
	Option           Hash = 0x65b06
	Output           Hash = 0x50d06
	P                Hash = 0xc01
	Param            Hash = 0xc05
	Pattern          Hash = 0x7807
	Pauseonexit      Hash = 0x5680b
	Ping             Hash = 0xad04
	Placeholder      Hash = 0xd20b
	Plaintext        Hash = 0x12e09
	Poster           Hash = 0x16e06
	Pre              Hash = 0x20303
	Preload          Hash = 0x20307
	Profile          Hash = 0x30e07
	Progress         Hash = 0x5a208
	Prompt           Hash = 0x35606
	Public           Hash = 0x39806
	Q                Hash = 0x9f01
	Radiogroup       Hash = 0x30a
	Readonly         Hash = 0x37e08
	Rel              Hash = 0x20403
	Required         Hash = 0x9d08
	Rev              Hash = 0x29403
	Reversed         Hash = 0x29408
	Rows             Hash = 0x5504
	Rowspan          Hash = 0x5507
	Rp               Hash = 0x28a02
	Rt               Hash = 0x1c502
	Ruby             Hash = 0x6504
	Rules            Hash = 0xdc05
	S                Hash = 0x2c01
	Samp             Hash = 0xaa04
	Sandbox          Hash = 0xe007
	Scope            Hash = 0x36005
	Scoped           Hash = 0x36006
	Script           Hash = 0x4f506
	Scrolling        Hash = 0x5d109
	Seamless         Hash = 0x3b108
	Section          Hash = 0xea07
	Select           Hash = 0x5ed06
	Selected         Hash = 0x5ed08
	Shape            Hash = 0x23905
	Size             Hash = 0x31e04
	Sizes            Hash = 0x31e05
	Small            Hash = 0x24305
	Sortable         Hash = 0x26c08
	Source           Hash = 0x32206
	Spacer           Hash = 0x69706
	Span             Hash = 0x5804
	Spellcheck       Hash = 0x3b80a
	Src              Hash = 0x45403
	Srcdoc           Hash = 0x45406
	Srclang          Hash = 0x49e07
	Start            Hash = 0x41505
	Step             Hash = 0x7504
	Strike           Hash = 0x5a906
	Strong           Hash = 0x67106
	Style            Hash = 0x67705
	Sub              Hash = 0x61403
	Summary          Hash = 0x67c07
	Sup              Hash = 0x68303
	Svg              Hash = 0x68603
	System           Hash = 0x68906
	Tabindex         Hash = 0x4cd08
	Table            Hash = 0x26f05
	Target           Hash = 0x2f906
	Tbody            Hash = 0x2e05
	Td               Hash = 0xc302
	Text             Hash = 0x13304
	Textarea         Hash = 0x37908
	Tfoot            Hash = 0xf705
	Th               Hash = 0x19302
	Thead            Hash = 0x69005
	Time             Hash = 0x1da04
	Title            Hash = 0x13605
	Tr               Hash = 0x15702
	Track            Hash = 0x15705
	Translate        Hash = 0x1c609
	Truespeed        Hash = 0x22909
	Tt               Hash = 0x7a02
	Type             Hash = 0x11604
	Typemustmatch    Hash = 0x1e80d
	U                Hash = 0xb01
	Ul               Hash = 0x4702
	Undeterminate    Hash = 0x17b0d
	Usemap           Hash = 0x14e06
	Valign           Hash = 0x5d06
	Value            Hash = 0x11105
	Valuetype        Hash = 0x11109
	Var              Hash = 0x33603
	Video            Hash = 0x69d05
	Visible          Hash = 0x6a807
	Vlink            Hash = 0x6af05
	Wbr              Hash = 0x56303
	Width            Hash = 0x5fa05
	Wrap             Hash = 0x39504
	Xmlns            Hash = 0xe605
	Xmp              Hash = 0x16c03
)

var _Hash_table = [1 << 9]Hash{
	0x0:   0x7e07,  // noembed
	0x1:   0x43010, // ondurationchange
	0x2:   0x30e07, // profile
	0x4:   0x3309,  // accesskey
	0x6:   0x68e04, // math
	0x7:   0x55a0a, // onpageshow
	0x8:   0x37602, // h4
	0x9:   0x6a107, // onclick
	0xa:   0xf705,  // tfoot
	0xc:   0x5060a, // onmouseout
	0xd:   0x5d06,  // valign
	0xe:   0x68303, // sup
	0xf:   0x19b07, // bgcolor
	0x10:  0x4307,  // default
	0x11:  0x1a207, // bgsound
	0x12:  0x4bf10, // onloadedmetadata
	0x13:  0x4b804, // list
	0x14:  0x2e302, // mn
	0x15:  0xbc05,  // frame
	0x16:  0x2b006, // object
	0x17:  0x5d109, // scrolling
	0x18:  0x45905, // class
	0x19:  0x39c04, // icon
	0x1a:  0x25508, // hreflang
	0x1c:  0x29c03, // for
	0x1e:  0x31e05, // sizes
	0x1f:  0x3c40d, // oncontextmenu
	0x21:  0x56607, // onpause
	0x22:  0x2ff02, // h6
	0x24:  0xef06,  // onblur
	0x25:  0x40f0b, // ondragstart
	0x26:  0x57f0e, // defaultChecked
	0x27:  0x25306, // nohref
	0x28:  0x4ac0c, // onloadeddata
	0x2a:  0x44e07, // onfocus
	0x2b:  0xc704,  // name
	0x2d:  0x1e80d, // typemustmatch
	0x2e:  0x601,   // i
	0x2f:  0x36608, // itemtype
	0x30:  0x32206, // source
	0x31:  0x5f506, // onshow
	0x33:  0x9505,  // aside
	0x36:  0x1ad05, // blink
	0x38:  0x1a802, // dl
	0x39:  0x64509, // onwaiting
	0x3c:  0x3b80a, // spellcheck
	0x3d:  0x61208, // onsubmit
	0x40:  0x7a02,  // tt
	0x41:  0x5ed08, // selected
	0x42:  0x56303, // wbr
	0x43:  0x19902, // h1
	0x44:  0x9106,  // canvas
	0x45:  0x6907,  // acronym
	0x46:  0x57108, // itemprop
	0x47:  0xb01,   // u
	0x48:  0x45f09, // draggable
	0x49:  0x1604,  // mark
	0x4d:  0x15702, // tr
	0x4e:  0x19302, // th
	0x4f:  0xb105,  // alink
	0x50:  0x58d09, // onplaying
	0x51:  0x4a507, // onkeyup
	0x53:  0x5e209, // onseeking
	0x54:  0x430f,  // defaultSelected
	0x55:  0x41707, // article
	0x57:  0x19d03, // col
	0x58:  0x36006, // scoped
	0x59:  0x31e04, // size
	0x5b:  0x4f506, // script
	0x5c:  0x15206, // applet
	0x5d:  0x45907, // classid
	0x5e:  0x101,   // b
	0x5f:  0x6370e, // onvolumechange
	0x60:  0x67c07, // summary
	0x64:  0x3d10b, // oncuechange
	0x65:  0x4d50b, // onloadstart
	0x66:  0x39806, // public
	0x67:  0x42208, // dropzone
	0x68:  0xc01,   // p
	0x69:  0x61e04, // face
	0x6a:  0x23e06, // coords
	0x6c:  0x26c08, // sortable
	0x6d:  0x41b05, // clear
	0x6e:  0x2807,  // charset
	0x71:  0x62609, // onsuspend
	0x72:  0x32d0a, // http-equiv
	0x73:  0x3906,  // keygen
	0x74:  0x41505, // start
	0x75:  0x1105,  // align
	0x76:  0x35205, // ismap
	0x77:  0x3ef0b, // ondragenter
	0x78:  0xb803,  // dfn
	0x79:  0x17b0d, // undeterminate
	0x7a:  0x10306, // itemid
	0x7c:  0x16607, // isindex
	0x7f:  0x31a08, // noresize
	0x80:  0x3fa0b, // ondragleave
	0x81:  0x4e90b, // onmousedown
	0x82:  0x7807,  // pattern
	0x83:  0x30906, // hgroup
	0x84:  0x27408, // fieldset
	0x85:  0x29403, // rev
	0x86:  0x4,     // abbr
	0x87:  0x44007, // onended
	0x88:  0x37805, // mtext
	0x89:  0x68906, // system
	0x8a:  0x5105,  // defer
	0x8c:  0x18a10, // oncanplaythrough
	0x8d:  0x8403,  // del
	0x8e:  0x1c502, // rt
	0x8f:  0x3e606, // ondrag
	0x96:  0x19402, // hr
	0x99:  0x5a906, // strike
	0x9a:  0xe605,  // xmlns
	0x9c:  0x2450f, // allowfullscreen
	0x9d:  0x22307, // compact
	0x9e:  0x1c007, // onabort
	0x9f:  0x66b07, // address
	0xa0:  0x4f308, // noscript
	0xa2:  0x10602, // mi
	0xa3:  0x39d0f, // contenteditable
	0xa4:  0x23905, // shape
	0xa5:  0x50d06, // output
	0xa6:  0x69005, // thead
	0xa9:  0x25504, // href
	0xab:  0x44707, // onerror
	0xad:  0x15c08, // autoplay
	0xaf:  0x3cd04, // menu
	0xb0:  0x10808, // disabled
	0xb2:  0x27c0a, // figcaption
	0xb3:  0x10f03, // div
	0xb5:  0x1d704, // font
	0xb8:  0xd20b,  // placeholder
	0xb9:  0x18203, // min
	0xba:  0x32804, // high
	0xbb:  0x4c704, // meta
	0xbd:  0x30504, // html
	0xbf:  0x6504,  // ruby
	0xc2:  0x5960a, // onpopstate
	0xc3:  0x2d60a, // formmethod
	0xc4:  0x53309, // onoffline
	0xc8:  0x2ba06, // action
	0xca:  0x24703, // low
	0xcb:  0x1,     // a
	0xcc:  0x34505, // image
	0xcd:  0x69106, // header
	0xce:  0x15705, // track
	0xcf:  0x57704, // open
	0xd0:  0x5fc02, // dt
	0xd1:  0x20303, // pre
	0xd2:  0x11a05, // audio
	0xd4:  0x5507,  // rowspan
	0xd5:  0x16c03, // xmp
	0xd6:  0x30a,   // radiogroup
	0xda:  0x28a02, // rp
	0xdb:  0x42709, // onemptied
	0xdc:  0x60009, // onstalled
	0xde:  0x1aa03, // big
	0xdf:  0x4950a, // onkeypress
	0xe3:  0x23208, // controls
	0xe4:  0x57a07, // noshade
	0xe5:  0x1a03,  // bdi
	0xe6:  0x36e03, // max
	0xe7:  0x100a,  // malignmark
	0xe9:  0x53e08, // ononline
	0xea:  0x4fb0b, // onmousemove
	0xed:  0x5b03,  // nav
	0xf2:  0x5270c, // onmousewheel
	0xf3:  0x18803, // bdo
	0xf4:  0x25904, // lang
	0xf5:  0x9702,  // id
	0xf6:  0x5fa05, // width
	0xf7:  0x18a09, // oncanplay
	0xf8:  0x12708, // optgroup
	0xf9:  0x4b408, // datalist
	0xfa:  0x61403, // sub
	0xfb:  0xc05,   // param
	0xfc:  0x1e408, // codetype
	0xfe:  0xf503,  // alt
	0xff:  0xc403,  // dir
	0x100: 0x5cf08, // onscroll
	0x102: 0x37908, // textarea
	0x104: 0x48809, // onkeydown
	0x107: 0x22909, // truespeed
	0x108: 0x5fe02, // h5
	0x10a: 0x2f906, // target
	0x10b: 0x3dc0a, // ondblclick
	0x10c: 0x45403, // src
	0x10d: 0x36e09, // maxlength
	0x10e: 0x8002,  // em
	0x10f: 0x39306, // nowrap
	0x111: 0x1202,  // li
	0x112: 0x20a04, // cols
	0x114: 0x35f02, // ms
	0x115: 0x68603, // svg
	0x116: 0xdc05,  // rules
	0x118: 0xe007,  // sandbox
	0x11a: 0x8605,  // label
	0x11c: 0xfe05,  // async
	0x11d: 0x2ea08, // datetime
	0x11e: 0xaa04,  // samp
	0x11f: 0x3ac07, // onclose
	0x120: 0xb204,  // link
	0x121: 0x2c01,  // s
	0x122: 0xc90a,  // mediagroup
	0x124: 0x2106,  // accept
	0x126: 0x1cf04, // code
	0x127: 0x20403, // rel
	0x128: 0x1b06,  // dialog
	0x129: 0x1d80c, // ontimeupdate
	0x12a: 0x2f50a, // formtarget
	0x12c: 0x60909, // onstorage
	0x12d: 0x5c708, // onresize
	0x12e: 0x5da08, // onseeked
	0x130: 0x4eb02, // mo
	0x131: 0x62006, // center
	0x134: 0x58d06, // onplay
	0x135: 0x2b604, // form
	0x136: 0x54e0c, // defaultMuted
	0x137: 0x8a08,  // longdesc
	0x138: 0x4b807, // listing
	0x139: 0x11604, // type
	0x13a: 0x16404, // axis
	0x13b: 0x12e09, // plaintext
	0x13c: 0x5c007, // onreset
	0x13d: 0x2da06, // method
	0x13e: 0x29408, // reversed
	0x13f: 0x38e05, // muted
	0x140: 0x5ed06, // select
	0x141: 0x1da04, // time
	0x142: 0x67106, // strong
	0x143: 0x69107, // headers
	0x144: 0x202,   // br
	0x146: 0xc905,  // media
	0x147: 0x10204, // cite
	0x149: 0x3e609, // ondragend
	0x14c: 0x26f05, // table
	0x14e: 0x14e06, // usemap
	0x14f: 0x13304, // text
	0x152: 0x25908, // language
	0x154: 0x3d07,  // enabled
	0x155: 0xb504,  // kind
	0x156: 0x12504, // loop
	0x157: 0x48d08, // download
	0x158: 0x36005, // scope
	0x15b: 0xf806,  // footer
	0x15c: 0x47a05, // input
	0x15d: 0x20f0a, // annotation
	0x15f: 0x37d04, // area
	0x160: 0xad04,  // ping
	0x163: 0x2e00e, // formnovalidate
	0x165: 0x65f0e, // onbeforeunload
	0x166: 0x5ad07, // keytype
	0x168: 0x2610b, // crossorigin
	0x169: 0x35002, // h3
	0x16b: 0xd802,  // ol
	0x16c: 0x3c60b, // contextmenu
	0x170: 0xc302,  // td
	0x171: 0x11109, // valuetype
	0x172: 0x39504, // wrap
	0x173: 0xbc08,  // frameset
	0x175: 0x16e06, // poster
	0x176: 0x37e08, // readonly
	0x178: 0x2840c, // onafterprint
	0x179: 0x11105, // value
	0x17a: 0x2a90d, // foreignobject
	0x17c: 0x26a03, // ins
	0x17d: 0x2be0d, // onbeforeprint
	0x17e: 0x15103, // map
	0x17f: 0x2f005, // meter
	0x182: 0x9d08,  // required
	0x184: 0x31506, // hidden
	0x187: 0x33a0b, // frameborder
	0x18a: 0x5804,  // span
	0x18c: 0x34a03, // img
	0x18e: 0xa407,  // details
	0x18f: 0x8005,  // embed
	0x190: 0x4b404, // data
	0x191: 0x34b06, // mglyph
	0x192: 0xea07,  // section
	0x193: 0x30106, // height
	0x194: 0x35c09, // itemscope
	0x195: 0x210e,  // accept-charset
	0x196: 0x46c0c, // onhashchange
	0x197: 0x19d05, // color
	0x198: 0x13b0c, // autocomplete
	0x199: 0x8e04,  // desc
	0x19a: 0x69104, // head
	0x19b: 0x69d05, // video
	0x19c: 0x4ac06, // onload
	0x19d: 0x4cd08, // tabindex
	0x19f: 0x2b60a, // formaction
	0x1a0: 0x31702, // dd
	0x1a1: 0x14709, // autofocus
	0x1a2: 0x5130b, // onmouseover
	0x1a3: 0x1b20a, // blockquote
	0x1a4: 0x1903,  // kbd
	0x1a6: 0x9807,  // declare
	0x1a7: 0x29c0d, // foreignObject
	0x1aa: 0x27f07, // caption
	0x1ad: 0x39d07, // content
	0x1ae: 0x20f0d, // annotationXml
	0x1af: 0x53905, // inert
	0x1b0: 0x20a07, // colspan
	0x1b1: 0x4702,  // ul
	0x1b2: 0x49e07, // srclang
	0x1b3: 0x5680b, // pauseonexit
	0x1b4: 0x47f09, // oninvalid
	0x1b5: 0x1fc08, // colgroup
	0x1b6: 0x33f06, // border
	0x1b7: 0x6204,  // nobr
	0x1b8: 0x42006, // ondrop
	0x1ba: 0x33906, // iframe
	0x1bb: 0x5eb08, // onselect
	0x1bc: 0x20307, // preload
	0x1bd: 0x6f08,  // manifest
	0x1c0: 0x1cf08, // codebase
	0x1c5: 0x51e09, // onmouseup
	0x1c6: 0x62f08, // onunload
	0x1c7: 0x5b40c, // onratechange
	0x1c8: 0x29006, // figure
	0x1ca: 0xc407,  // dirname
	0x1cc: 0x1bc06, // button
	0x1cd: 0xba08,  // noframes
	0x1ce: 0x13605, // title
	0x1cf: 0x2cb0b, // formenctype
	0x1d1: 0x43808, // onchange
	0x1d2: 0x6af05, // vlink
	0x1d4: 0x69706, // spacer
	0x1d5: 0x4050a, // ondragover
	0x1d6: 0x32b02, // h2
	0x1d7: 0x3b108, // seamless
	0x1d8: 0x65407, // marquee
	0x1d9: 0x46606, // legend
	0x1da: 0x3bd07, // checked
	0x1db: 0x5a208, // progress
	0x1dd: 0x67705, // style
	0x1de: 0x35606, // prompt
	0x1df: 0x7504,  // step
	0x1e1: 0x65b06, // option
	0x1e2: 0x5460a, // onpagehide
	0x1e4: 0x45406, // srcdoc
	0x1e7: 0x47807, // oninput
	0x1e8: 0x4e009, // onmessage
	0x1e9: 0x2e40a, // novalidate
	0x1ea: 0x2cf07, // enctype
	0x1eb: 0x1d308, // basefont
	0x1ec: 0x38608, // multiple
	0x1ed: 0x5504,  // rows
	0x1ee: 0x1c609, // translate
	0x1ef: 0x11e08, // oncancel
	0x1f0: 0x21c07, // command
	0x1f1: 0x1f309, // challenge
	0x1f2: 0x2e05,  // tbody
	0x1f4: 0x2f04,  // body
	0x1f5: 0x6a807, // visible
	0x1f6: 0x1d304, // base
	0x1f7: 0x33603, // var
	0x1f8: 0x61807, // itemref
	0x1f9: 0x64e07, // optimum
	0x1fb: 0x9f01,  // q
	0x1fc: 0x1740a, // background
	0x1fe: 0x5a00a, // onprogress
	0x1ff: 0x24305, // small
}
